print("Hello Gaurav")
print("hi whats up")
print("Hello Gaurav")
print("hi whats up")
print("Hello Gaurav")
print("hi whats up")
print("Hello Gaurav")
print("hi whats up")
print("Hello Gaurav")
print("hi whats up")
print("Hello Gaurav")
print("hi whats up")
print("this is line ")